# Generated by Django 3.2.5 on 2021-07-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortener',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='shortener',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='shortener',
            name='times_followed',
        ),
        migrations.AlterField(
            model_name='shortener',
            name='long_url',
            field=models.URLField(max_length=500),
        ),
    ]
