# Generated by Django 3.2.5 on 2021-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_auto_20210724_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
